# Generated by Django 3.1 on 2020-10-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuschecks',
            options={'ordering': ['name', 'taskname', 'cmd_regex']},
        ),
        migrations.AlterModelOptions(
            name='statusfiles',
            options={'get_latest_by': 'task_finished_time', 'ordering': ['task_finished_time', 'check_name', 'cmd']},
        ),
    ]
