# Generated by Django 3.1 on 2020-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschecks',
            name='max_age',
            field=models.IntegerField(choices=[(70, 'Stündlich'), (1460, 'Täglich'), (10100, 'Wöchentlich')], default=70),
        ),
    ]
