[package]
name = "spatial-rust-util"
version = "0.1.1"
authors = ["Daniel Naschberger <daniel@naschi.at>"]
edition = "2021"

[lib]
name = "spatial_rust_util"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.19"
libmath = "0.2.1"
pyo3 = { version = "0.15.1", features = ["extension-module"] }
