version: '3.7'

volumes:
  get_available_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/get_available_data
  log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/log
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/media
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/static
  spool:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/spool
  postgresdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresdata
  postgres_backup_server:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresdata_backup_server
  py_spatialmos:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/py_spatialmos


services:  
  py_pre_processing_gefs:
    build: ./container/py_pre_processing_gefs/
    container_name: spatialMOS_py_pre_processing_gefs
    volumes:
      - get_available_data:/get_available_data
      - log:/log
      - py_spatialmos:/usr/src/app/py_spatialmos