version: '3.7'

volumes:
  log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/log
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/media
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/static
  spool:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/spool
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresdata
  postgres_backup_server:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresdata_backup_server
  py_spatialmos:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/py_spatialmos
  r_spatialmos:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/r_spatialmos
  get_available_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/get_available_data
  spatialmos_climatology:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/spatialmos_climatology
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/django
  node:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/container/node

services:
  django:
    build:
      target: development

  node:
    restart: always
    build: ./container/node/
    container_name: spatialMOS_node
    user: "${USERID}:${GROUPID}"
    ports:
      - 80:8080
    volumes:
      - node:/www/
      - django:/www/site:z
      - static:/www/static:z
      - log:/log:z

  r_base:
    build: ./container/r_base/
    container_name: spatialMOS_r_base
    volumes:
      - log:/log:z
      - r_spatialmos:/usr/src/app/r_spatialmos:z
      - get_available_data:/usr/src/app/data/get_available_data:z
      - spatialmos_climatology:/usr/src/app/data/spatialmos_climatology:z
      - static:/usr/src/app/data/static:z

  py_pre_processing_topography:
    build: ./container/py_gdal/
    container_name: spatialMOS_py_pre_processing_topography
    volumes:
      - log:/log:z
      - py_spatialmos:/usr/src/app/py_spatialmos:z
      - get_available_data:/usr/src/app/data/get_available_data:z

  nginx:
    restart: always
    container_name: spatialMOS_nginx
    build:
      context: "./container/nginx"
      args: 
        NGINX_CONF: ${NGINX_CONF}
    volumes:
      - static:/www/static:z
      - media:/www/media:z
      - log:/log:z