version: '3.7'

volumes:
  log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/log
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/media
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/static
  spool:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/spool
  postgresdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresdata
  postgres_backup_server:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgresdata_backup_server
  py_spatialmos:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/py_spatialmos
  r_spatialmos:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/r_spatialmos
  get_available_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/get_available_data
  spatialmos_climatology:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/spatialmos_climatology


services:  
  r_spatialmos_climatology:
    build: ./container/r_spatialmos_climatology/
    container_name: spatialMOS_r_spatialmos_climatology
    volumes:
      - log:/log:z
      - r_spatialmos:/usr/src/app/r_spatialmos:z
      - get_available_data:/usr/src/app/data/get_available_data:z
      - spatialmos_climatology:/usr/src/app/data/spatialmos_climatology:z
      - static:/usr/src/app/data/static:z

  py_pre_processing_topography:
    build: ./container/py_gdal/
    container_name: spatialMOS_py_pre_processing_topography
    volumes:
      - log:/log:z
      - py_spatialmos:/usr/src/app/py_spatialmos:z
      - get_available_data:/usr/src/app/data/get_available_data:z