version: '3.7'

services:  
  py_requests:
    build: ./container/py_requests/
    container_name: spatialMOS_py_requests
    volumes:
      - log:/log:z
      - py_spatialmos:/usr/src/app/py_spatialmos:z
      - get_available_data:/usr/src/app/data/get_available_data:z
  
  py_wgrib2:
    build: ./container/py_wgrib2/
    container_name: spatialMOS_py_wgrib2
    volumes:
      - log:/log:z
      - py_spatialmos:/usr/src/app/py_spatialmos:z
      - get_available_data:/usr/src/app/data/get_available_data:z
  
  py_cartopy:
    build: ./container/py_cartopy/
    container_name: spatialMOS_py_cartopy
    volumes:
      - log:/log:z
      - py_spatialmos:/usr/src/app/py_spatialmos:z
      - get_available_data:/usr/src/app/data/get_available_data:z
      - spatialmos_climatology:/usr/src/app/data/spatialmos_climatology:z
      - spool:/usr/src/app/data/spool:z
  
  py_cfgrib:
    build: ./container/py_cfgrib/
    container_name: py_cfgrib
    volumes:
      - log:/log:z
      - spatialmos_climatology:/usr/src/app/data/spatialmos_climatology:z
      - py_spatialmos:/usr/src/app/py_spatialmos:z
      - get_available_data:/usr/src/app/data/get_available_data:z

  django:
    restart: always
    build: ./django/
    container_name: spatialMOS_django
    expose:
      - "8000"
    user: "${USERID}:${GROUPID}"
    volumes:
      - django:/www/site:z
      - static:/www/static:z
      - media:/www/media:z
      - spool:/www/data/spool:z
      - log:/log:z
    depends_on:
      - postgres

  postgres:
    restart: always
    build: "./container/postgres"
    container_name: spatialMOS_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
      - postgres_backup:/var/backup:z
