on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

name: maturin

jobs:
  maturin:
    name: maturin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true
    - name: Rust check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        args: --release --manylinux off
    - name: cache maturin builds
      uses: actions/cache@v2
      id: restore-maturin-build
      with:
        path: ./target
        key: ${{ github.sha }}

  pylint:
    name: pylint
    needs: maturin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
  
    steps:
    - name: git checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.maturin.outputs.branch }}
    - name: update ubuntu
      run: |
        sudo apt-get update -y
    - name: cache maturin builds
      uses: actions/cache@v2
      id: restore-maturin-build
      with:
        path: ./target
        key: ${{ github.sha }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint requests pytz invoke pytest
        pip install ./target/wheels/spatial_rust_util-0.1.1-cp39-cp39-linux_x86_64.whl
    - name: Lint fabric
      run: |
        pylint fabric/
        pylint task.py
    - name: Lint py_spatialmos
      run: |
        pylint --exit-zero py_spatialmos/
        pylint --exit-zero run_script.py
    - name: Lint tests
      run: |
        pylint tests/

  pytest:
    name: pytest
    needs: maturin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: update ubuntu
      run: |
        sudo apt-get update -y
    - name: git checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.maturin.outputs.branch }}
    - name: cache maturin builds
      uses: actions/cache@v2
      id: restore-maturin-build
      with:
        path: ./target
        key: ${{ github.sha }}
    - name: copy spatial_rust_util
      run: |
        ls ./target/wheels/
        cp ./target/wheels/spatial_rust_util-0.1.1-cp39-cp39-linux_x86_64.whl .
    - name: get gadm36_AUT_shp
      run: |
        sudo apt-get install -y wget unzip
        cd ./tests/testdata/test_prediction/
        mkdir gadm36_AUT_shp
        wget https://biogeo.ucdavis.edu/data/gadm3.6/shp/gadm36_AUT_shp.zip
        unzip gadm36_AUT_shp.zip -d gadm36_AUT_shp
        ls ./gadm36_AUT_shp
    - name: get image-optimizer
      run: curl -L https://github.com/naschidaniel/image-optimizer/releases/download/main/image-optimizer-linux --output image-optimizer && chmod +x image-optimizer
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt-get install -y libeccodes-tools  
        sudo apt-get install gdal-bin libeccodes0 libgdal-dev libproj-dev proj-bin proj-data libgeos-dev -y
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r ./container/py_container/requirements.txt
        pip install cartopy
        cp ./fabric/settings.example.json settings.json
    - name: Test with pytest
      run: |
        pytest --cov=py_spatialmos ./tests/