on:
  workflow_run:
    workflows: ["maturin"]
    types: [completed]

name: mypy

jobs:
  pylint:
    name: mypy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: cache maturin builds
      uses: actions/cache@v2
      id: restore-maturin-build
      with:
        path: ./target
        key: ${{ github.sha }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        pip install ./target/wheels/spatial_rust_util-0.1.0-cp39-cp39-linux_x86_64.whl
    - name: Lint run_get_data
      run: |
        mypy --junit-xml report.xml *.py py_spatialmos/
