on:
  workflow_run:
    workflows: ["maturin"]
    types: [completed]

name: pytest

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: cache maturin builds
      uses: actions/cache@v2
      id: restore-maturin-build
      with:
        path: ./target
        key: ${{ github.sha }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests pytz
        cp ./fabric/settings.example.json settings.json
        ls ./target/wheels/
        pip install ./target/wheels/spatial_util-0.1.0-cp39-cp39-manylinux_2_24_x86_64.whl
    - name: Test with pytest
      run: |
        pytest ./tests
