on:
  workflow_run:
    workflows: ["maturin"]
    types: [completed]

name: pytest

jobs:
  pytest:
    name: pytest get data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: update ubuntu
      run: |
        sudo apt-get update -y
    - uses: actions/checkout@v2
    - name: cache maturin builds
      uses: actions/cache@v2
      id: restore-maturin-build
      with:
        path: ./target
        key: ${{ github.sha }}
    - name: copy spatial_rust_util
      run: |
        ls ./target/wheels/
        cp ./target/wheels/spatial_rust_util-0.1.1-cp39-cp39-linux_x86_64.whl .
    - name: get gadm36_AUT_shp
      run: |
        sudo apt-get install -y wget unzip
        cd ./tests/testdata/test_prediction/
        mkdir gadm36_AUT_shp
        wget https://biogeo.ucdavis.edu/data/gadm3.6/shp/gadm36_AUT_shp.zip
        unzip gadm36_AUT_shp.zip -d gadm36_AUT_shp
        ls ./gadm36_AUT_shp
    - name: get image-optimizer
      run: curl -L https://github.com/naschidaniel/image-optimizer/releases/download/main/image-optimizer-linux --output image-optimizer && chmod +x image-optimizer
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt-get install -y libeccodes-tools  
        sudo apt-get install gdal-bin libeccodes0 libgdal-dev libproj-dev proj-bin proj-data libgeos-dev -y
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r ./container/py_container/requirements.txt
        pip install cartopy
        cp ./fabric/settings.example.json settings.json
    - name: Test with pytest
      run: |
        pytest --cov=py_spatialmos ./tests/
