on: [push, pull_request]

name: py_spatialmos requests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install stable rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest invoke
        pip install -r ./container/py_requests/requirements.txt
        ./task.py local.spatialmos.py-spatialmos--maturin-build
    # - name: Lint with pylint
    #   run: |
    #     pylint py_spatialmos/get_lwd_data.py
    #     pylint py_spatialmos/get_suedtirol_data.py
    #     pylint py_spatialmos/get_zamg_data.py
    - name: Test with pytest
      run: |
        pytest ./tests
