on: [push, pull_request]

name: py_spatialmos requests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: addnab/docker-run-action@v3
      name: Run maturin
      with:
        image: konstin2/maturin
        options: -v ${{ github.workspace }}:/io
        run: |
          echo "Running maturin build container"
          build
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install invoke requests
        cp ./fabric/settings.example.json settings.json
        pip install -r ./container/py_requests/requirements.txt
        mv ./target/wheels/*.whl ./container/py_requests/
    # - name: Lint with pylint
    #   run: |
    #     pylint py_spatialmos/get_lwd_data.py
    #     pylint py_spatialmos/get_suedtirol_data.py
    #     pylint py_spatialmos/get_zamg_data.py
    - name: Test with pytest
      run: |
        pytest ./tests
